name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    - name: Run update.py
      run: |
        python update.py
    - name: Check for changes
      run: git status
    - name: Commit changes
      run: |
        git config --global user.name 'hayeon00'
        git config --global user.email 'gimhayeon38@gmail.com'
        git diff --quiet || (git add -A && git commit -m "auto update README.md")
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
